version: '3.9'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose images
# docker-compose logs --tail 20 repo_name

services:

  postgres_db:
    image: postgres:latest
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: "iPkt9FsmoQ7*xdGr"
      POSTGRES_DB: tie_crawler
      POSTGRES_USER: tie
    ports:    # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  tie-crawler:
    build:
      context: ./app
      dockerfile: ./DOCKERFILE
    ports:
      - "8501:8501"
    depends_on:
      - postgres_db
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge