version: '3.9'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs

services:

  postgres_db:
    image: postgres:latest
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: "iPkt9FsmoQ7*xdGr"
      POSTGRES_DB: tie_crawler
      POSTGRES_USER: tie
    ports:    # Set up ports exposed for other containers to connect to
      - 15433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  pg_admin:
    image: dpage/pgadmin4:latest
    environment:   # Set up pg_admin user and password
      PGADMIN_DEFAULT_EMAIL: mail@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:    # Set up ports exposed for other containers to connect to
      - 5480:80
    depends_on:
      - postgres_db
    networks:
      - app-tier
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  tie-crawler:
    build:
      context: .
      dockerfile: ./DOCKERFILE
    ports:
      - "8501:8501"
    depends_on:
      - postgres_db
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge