version: '3.9'

# Run as
# docker-compose build; docker-compose up -d

services:

  postgres_db:
    image: postgres:latest
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: "iPkt9FsmoQ7*xdGr"
      POSTGRES_DB: tie_crawler
      POSTGRES_USER: tie
    ports:    # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  pg_admin:
    image: dpage/pgadmin4:latest
    environment:   # Set up pg_admin user and password
      PGADMIN_DEFAULT_EMAIL: mail@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:    # Set up ports exposed for other containers to connect to
      - 5480:80
    depends_on:
      - postgres_db
    networks:
      - app-tier
    volumes:
      - ./servers_local_dev.json:/pgadmin4/servers.json


networks:
  app-tier:
    driver: bridge